// @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from docs/001-project-setup
    },
  ],
};

module.exports = sidebars;
